# SwiftLint Configuration for IPCrypt

# Paths
included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift
  - Tests/IPCryptTests/test_vectors.json

# Rules
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - todo
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - force_cast
  - force_try

# Rule Configuration
identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - ip
    - iv
    - k1
    - k2
    - et
    - s0
    - s1
    - s2
    - s3

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

nesting:
  type_level:
    warning: 2
    error: 3

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

